version: '3.4'

services:
  envoygateway:
        build: Envoy/
        ports:
          - "9903:9903"
          - "10001:10000"
        networks:
          - piensaperu
        volumes:
          - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
  piensaperu.administrationservice:
    image: ${DOCKER_REGISTRY-}piensaperuadministratorservice
    build:
      context: .
      dockerfile: PiensaPeru.AdministratorService/Dockerfile
    ports:
      - '8091:80'
    networks:
      - piensaperu
  
  piensaperu.usersservice:
    image: ${DOCKER_REGISTRY-}piensaperuusersservice
    build:
      context: .
      dockerfile: PiensaPeru.UsersService/Dockerfile
    ports:
      - '8092:80'
    networks:
      - piensaperu

  piensaperu.content:
    image: ${DOCKER_REGISTRY-}piensaperucontent
    build:
      context: .
      dockerfile: PiensaPeru.Content/Dockerfile
    ports:
      - '8086:80'
    networks:
      - piensaperu


  piensaperu.supervisor:
    image: ${DOCKER_REGISTRY-}piensaperusupervisor
    build:
      context: .
      dockerfile: PiensaPeru.Supervisor/Dockerfile
    ports:
      - '8088:80'
    networks:
      - piensaperu

networks:
  piensaperu: